src/Entity/Stars.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\StarsRepository")
 */
class Stars
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;
    /**
     * @ORM\Column(type="string", length=255)
     */
    private $avatar;
    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Movies", mappedBy="stars")
     */
    private $movies;
     /**
     * @ORM\OneToMany(targetEntity="App\Entity\Series", mappedBy="Movies")
     */
    private $series;
    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Producent", mappedBy="stars")
     */
    private $Producents;


    public function __construct()
    {
        $this->movies = new ArrayCollection();
        $this->nproducents = new ArrayCollection();
        $this->newProducents = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }
    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }
    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(string $name): self
    {
        $this->avatar = $name;

        return $this;
    }
    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $name): self
    {
        $this->description = $name;

        return $this;
    }
    public function getProducent(): ?Producent
    {
        return $this->testtable;
    }
    /**
     * @return Collection|Movies[]
     */
    public function getMovies(): Collection
    {
        return $this->movies;
    }

    public function addMovie(Movies $movie): self
    {
        if (!$this->movies->contains($movie)) {
            $this->movies[] = $movie;
            $movie->addStar($this);
        }

        return $this;
    }

    public function removeMovie(Movies $movie): self
    {
        if ($this->movies->contains($movie)) {
            $this->movies->removeElement($movie);
            $movie->removeStar($this);
        }

        return $this;
    }
    public function getSeries(): Collection
    {
        return $this->series;
    }

    public function addSeries(Movies $movie): self
    {
        if (!$this->series->contains($movie)) {
            $this->series[] = $movie;
            $movie->setSeries($this);
        }

        return $this;
    }

    public function removeSeries(Movies $movie): self
    {
        if ($this->movies->contains($movie)) {
            $this->movies->removeElement($movie);
            // set the owning side to null (unless already changed)
            if ($movie->getSeries() === $this) {
                $movie->setSeries(null);
            }
        }

        return $this;
    }
    
    public function __toString(){
        return $this->name;
    }
    /**
     * @return Collection|Producent[]
     */
    public function getProducents(): Collection
    {
        return $this->newProducents;
    }

    public function addProducent(Producent $Producent): self
    {
        if (!$this->Producents->contains($Producent)) {
            $this->Producents[] = $Producent;
            $Producent->addStar($this);
        }

        return $this;
    }

    public function removeNewProducent(NewProducent $newProducent): self
    {
        if ($this->Producents->contains($Producent)) {
            $this->Producents->removeElement($Producent);
            $Producent->removeStar($this);
        }

        return $this;
    }
}

templates/navigation/itemlist.html.twig
{% extends 'base.html.twig' %}
{% block title %}{{twing.sectionName}}{% endblock %}
{% block body %}
    <h2>{{twing.sectionName}}</h2>
    <div class="cradSection">
        {% for el in results %}
            <div class="card">
                <img src="{{ asset(twing.photourl ~ '/' ~  el.avatar) }}" class="card-img-top" width="100" height="100" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{el.name}}</h5>
                    <p class="card-text">{{el.description}}</p>
                    <div class="actionMenu">
                        <a href="{{path(twing.url,{id:el.id})}}" class="btn btn-secondary btn-sm">Show</a>
                        <a href="{{path(twing.editLink,{id:el.id})}}" class="btn btn-primary btn-sm">Edit</a>
                        <a href="{{path(twing.deleteLink,{id:el.id})}}" class="btn btn-danger btn-sm">Delete</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="navigation pagination" >
        {{ knp_pagination_render(results) }}
    </div>
{% endblock %}

templates/navigation/movielist.html.twig
{% extends 'base.html.twig' %}
{% block title %}Hello SeriesController!{% endblock %}
{% block body %}
    <h2>{{twing.sectionName}}</h2>
    <div class="cradSection">
        {% for el in item %}
            <div class="card">
                <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" src="{{el.linkSrc}}" class="card-img-top" allowfullscreen></iframe>
                </div>
                <div class="card-body">
                    <h5 class="card-title">{{el.name}}</h5>
                    <a href="{{path('show_movie',{id:el.id})}}" class="btn btn-secondary btn-sm">Show</a>
                    <a href="{{path(twing.editLink,{id:el.id})}}" class="btn btn-primary btn-sm">Edit</a>
                    <a href="{{path(twing.deleteLink,{id:el.id})}}" class="btn btn-danger btn-sm">Delete</a>
                </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/navigation/show_movie.htm.twig
{% extends 'base.html.twig' %}
{% block title %}{{movie.name}}{% endblock %}
{% block body %}
    <div class="row">
        <div class="col-7">
            <div class="videoSection">
                    <div class="embed-responsive embed-responsive-16by9 videoItem" >
                        <iframe class="embed-responsive-item" src="{{movie.linkSrc}}" allowfullscreen></iframe>
                    </div>
                <nav class="navbar navbar-light bg-light">
                    <a class="navbar-brand">Action</a>
                        <form class="form-inline actionlist">
                          <a href="{{path('editMovies',{id:movie.id})}}" class="btn btn-primary btn-sm">Edit</a>
                          <a href="{{path('editMovies',{id:movie.id})}}" class="btn btn-danger btn-sm">Delete</a>
                        </form>
                </nav>
                <table class="table">
                    <tbody>
                       <tr>
                         <td>Title</td>
                         <td>{{movie.name}}</td>
                      </tr>
                      <tr>
                          <td>Description</td>
                          <td><i>{{movie.description}}</i></td>
                      </tr>
                      {% if movie.producent%}
                      <tr>
                        <td>Producent</td>
                            <td><a href="{{path('faindProducents',{searchvalue:movie.producent})}}">{{movie.producent}}</a></td>
                      </tr>
                      {% endif %}
                      {% if movie.series%}
                      <tr>
                        <td>Series</td>

                        <td><a href="{{path('faindSeries',{searchvalue:movie.series})}}">{{movie.series}}</a></td>
                      </tr>
                      {% endif %}
                      <tr>
                        <td>Categorys</td>
                        <td>
                            {% for el in tags %}
                                <a href="{{path('show_movies_in_category',{id:el.id})}}">{{el}}</a>
                            {% endfor %}
                        </td>
                      </tr>
                      <tr>
                        <td>Stars</td>
                        <td>
                            {% for el in stars %}
                                <a href="{{path('show_movies_with_star',{id:el.id})}}">{{el}}</a>
                            {% endfor %}
                        </td>
                      </tr>
                      <tr>
                        <td>Adddate</td>
                        <td>
                            {{ movie.time | date('Y-m-d') }}, {{ movie.time | date('H:i:s') }}
                        </td>
                      </tr>
                      <tr>
                        <td>views</td>
                        <td>{{movie.views}}</td>
                      </tr>
                    </tbody>
                  </table>
            </div>
        </div>
        <div class="col-5">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="nav-item">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">Movies with thee stars</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">tags</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">sereis</a>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                    {% for el in stars_in_movies %}
                        <div class="row similarList">
                            <div class="col-4">
                                    {% if el.link%}
                                         <div class="embed-responsive embed-responsive-16by9 videoItem" >
                                            <iframe class="embed-responsive-item" src="{{el.linkSrc}}" allowfullscreen></iframe>
                                        </div>
                                    {% else %}
                                        <video  controls class="videoItem">
                                            <source src="{{el.movieSrc}}" >
                                        </video>
                                   {% endif %}
                            </div>
                            <div class="col-8"><a  dolongfilter href="{{path('show_movie',{id:el.id})}}">{{el.name}}</a>
                                <div> views : {{el.views}}</div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                    {% for el in tags_in_movies %}
                        <div class="row similarList">
                            <div class="col-4">
                                    {% if el.link%}
                                         <div class="embed-responsive embed-responsive-16by9 videoItem" >
                                            <iframe class="embed-responsive-item" src="{{el.linkSrc}}" allowfullscreen></iframe>
                                        </div>
                                    {% else %}
                                        <video  controls class="videoItem">
                                            <source src="{{el.movieSrc}}" >
                                        </video>
                                   {% endif %}
                            </div>
                            <div class="col-8">
                                <a dolongfilter href="{{path('show_movie',{id:el.id})}}">{{el.name}} </a>
                                <div> views : {{el.views}}</div>
                            </div>  
                        </div>
                    {% endfor %}
                </div>
                <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">
                    {% for el in movies_in_serie %}
                        <div class="row similarList">
                            <div class="col-4">
                                    {% if el.link%}
                                         <div class="embed-responsive embed-responsive-16by9 videoItem" >
                                            <iframe class="embed-responsive-item" src="{{el.linkSrc}}" allowfullscreen></iframe>
                                        </div>
                                    {% else %}
                                        <video  controls class="videoItem">
                                            <source src="{{el.movieSrc}}" >
                                        </video>
                                   {% endif %}
                            </div>
                            <div class="col-8"><a dolongfilter href="{{path('show_movie',{id:el.id})}}">{{el.name}}</a>
                               <div> views : {{el.views}}</div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/navigation/showmovies.htm.twig
{% extends 'base.html.twig' %}
{% block title %}{{twing.sectionName}}{% endblock %}
{% block body %}
    <h2>{{twing.sectionName}}</h2>
    <div class="cradSection">
        {% for el in results %}
            <div class="card">
                <div class="embed-responsive embed-responsive-16by9">
                    <iframe class="embed-responsive-item" src="{{el.linkSrc}}" class="card-img-top" allowfullscreen></iframe>
                </div>
                <div class="card-body">
                    <div class="card-title"><b>{{el.name}}</b></div>
                    <a href="{{path(twing.url,{id:el.id})}}" class="btn btn-secondary btn-sm">Show</a>
                    <a href="{{path(twing.editLink,{id:el.id})}}" class="btn btn-primary btn-sm">Edit</a>
                    <a href="{{path(twing.deleteLink,{id:el.id})}}" class="btn btn-danger btn-sm">Delete</a>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="navigation">
        {{ knp_pagination_render(results) }}
    </div>
{% endblock %}